apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: frontend
        version: 1.0.0
    spec:
      containers:
        - name: frontend
          image: bijoydocker/kubernetes-beginner-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      nodeSelector:
        node-type: app