apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  annotations:
    description: Frontend Deployment with RollingUpdate Change
    commit_id: kgfdsdfsd212j
spec:
  selector:
    matchLabels:
      name: frontend
      app: frontend
      version: 1.0.0
  replicas: 1
  revisionHistoryLimit: 5                     #default 10
  progressDeadlineSeconds: 60                 #default 600
  strategy:
    type: RollingUpdate   ##Or Recreate
    rollingUpdate:   
      maxSurge: 100%      # default 25%
      maxUnavailable: 0   # default 25%
  template:
    metadata:
      # namespace: dev
      labels:
        app: frontend
        name: frontend
        version: 1.0.0
    spec:
      containers:
        - name: frontend
          image: bijoydocker/kubernetes-beginner-frontend:advance
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # https://medium.com/spire-labs/utilizing-kubernetes-liveness-and-readiness-probes-to-automatically-recover-from-failure-2fe0314f2b2e
          # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#probe-v1-core
          # https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
          # Indicates whether the Container is running. 
          # If the liveness probe fails, the kubelet kills the Container, and the Container is subjected to its restart policy. 
          # If a Container does not provide a liveness probe, the default state is Success.
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              # httpHeaders:
              # - name: Custom-Header
              #   value: Awesome
            # it is recommended to allow enough time for the Readiness Probe to possibly fail a few times before a pass,
            # and only then check the Liveness Probe.
            initialDelaySeconds: 75 # default is 0
            periodSeconds: 30 #default is 10
            timeoutSeconds: 5 #default is 1
            successThreshold: 1 # default is 1
            failureThreshold: 3 # default is 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              # httpHeaders:
              # - name: Custom-Header
              #   value: Awesome
            initialDelaySeconds: 10 # default is 0
            periodSeconds: 5 #default is 10
            timeoutSeconds: 5 #default is 1
            successThreshold: 3 # default is 1
            failureThreshold: 5 # default is 3
      nodeSelector:
        node-role.kubernetes.io/node: app