apiVersion: apps/v1 
kind: Deployment
metadata:
  name: writer
spec:
  selector:
    matchLabels:
      app: writer
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: writer
        version: 1.0.0
    spec:
      containers:
        - name: writer
          image: bijoydocker/kubernetes-beginner-writer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
              # Use secret in real usage
            - name: APP_PORT
              value: "8081"
            - name: API_PATH
              value: /writer
            - name: MONGO_HOST
              value: db
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: root
            - name: MONGO_PASSWORD
              value: example
            - name: RABBIT_HOST
              value: queue
            - name: RABBIT_PASSWORD
              value: "5672"
            - name: RABBIT_USER
              value: user
            - name: RABBIT_PASSWORD
              value: password
            - name: QUEUE_NAME
              value: contact_event_queue
      nodeSelector:
        node-type: app