apiVersion: v1   ## equicalent to kubectl expose deployment/my-nginx
kind: Service
metadata:
  name: cache
spec:
  clusterIP: None
  selector:
    app: cache
  ports:
    - name: tcp
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
  
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: cache
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: cache
        name: cache
        version: 1.0.0
    spec:
      containers:
        - name: redis
          image: redis:5.0.4
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
          - name: MASTER
            value: "true"
          ports:
          - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
          - mountPath: /redis-master-data
            name: data
          - mountPath: /redis-master
            name: config
        volumes:
          - name: data
            emptyDir: {}
          - name: config
            configMap:
              name: example-redis-config
              items:
              - key: redis-config
                path: redis.conf