apiVersion: v1   ## equicalent to kubectl expose deployment/my-nginx
kind: Service
metadata:
  name: mongo
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: db
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: db
        name: mongo
        version: 1.0.0
    spec:
      containers:
        - name: db
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
              # Use secret in real usage
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          volumeMounts:
          - name: db-data
            mountPath: /data/db
      volumes:
        - name: db-data
          emptyDir: {}
      nodeSelector:
        node-role.kubernetes.io/node: storage