---
apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  clusterIP: None
  selector:
    app: amqp
  ports:
    - name: api
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: amqp
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: amqp
        name: queue
        version: 1.0.0
    spec:
      containers:
        - name: amqp
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
              # Use secret in real usage
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
          volumeMounts:
          - name: queue-data
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: queue-data
          emptyDir: {}
      nodeSelector:
        node-role.kubernetes.io/node: storage