---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-sg
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          type: ingress
    ports:
    - protocol: TCP
      port: 3000