---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: writer-sg
spec:
  podSelector:
    matchLabels:
      app: writer
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          type: ingress
    ports:
    - protocol: TCP
      port: 8081
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: db
    ports:
    - protocol: TCP
      port: 27017
  - to:
    - podSelector:
        matchLabels:
          name: queue
    ports:
    - protocol: TCP
      port: 15672
    - protocol: TCP
      port: 5672