kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
   proxy_set_header: "X-Forwarded-Host $host"
   proxy_set_header: "X-Forwarded-Proto $scheme"
   proxy_set_header: "X-Real-IP          $remote_addr"
   proxy_set_header: "X-Forwarded-Server $host"
   proxy_set_header: "Host               $http_host"
   proxy_set_header: "X-Forwarded-For    $proxy_add_x_forwarded_for"
   proxy_set_header: "Upgrade $http_upgrade"
   proxy_set_header: "Connection "upgrade"
   proxy_connect_timeout: "600"
   proxy_send_timeout: "600"
   proxy_read_timeout: "600"
   send_timeout: "600"
   proxy_buffers: "8 32k"
   proxy_buffer_size: "64k"
   