kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
  labels:
    app.kubernetes.io/name: nginx-config
    app.kubernetes.io/part-of: nginx-ingress
data:
  ssl_session_cache: "shared:SSL:50m"
  ssl_session_timeout: "1d"
  ssl_session_tickets: "off"
  ssl_prefer_server_ciphers: "on"
  ssl_ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:@STRENGTH"
  proxy_ssl_protocols: "TLSv1.1 TLSv1.2"
  proxy_ssl_ciphers: "HIGH:!aNULL:!MD5"
  proxy_connect_timeout: "600"
  proxy_send_timeout: "600"
  proxy_read_timeout: "600"
  send_timeout: "600"
  proxy_buffers: "8 32k"
  proxy_buffer_size: "64k"
  proxy-set-headers: "nginx-ingress/nginx-proxy-headers"
  
   