apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress 
  labels:
    name: nginx-ingress 
    type: ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress 
  namespace: nginx-ingress