apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
  #     # Which port on the node is the service available through?
      # nodePort: 31236 #optional, if skipped random port will allocate(default: 30000-32767)
      # Inside the cluster, what port does the service expose?
      port: 3000
      # Which port do pods selected by this service expose?
      targetPort: 3000
  type: ClusterIP
