apiVersion: v1
kind: Service
metadata:
  name: reader
spec:
  selector:
    app: reader
  ports:
    - name: http
      protocol: TCP
  #     # Which port on the node is the service available through?
  #     nodePort: 31234 #optional, if skipped random port will allocate(default: 30000-32767)
      # Inside the cluster, what port does the service expose?
      port: 8080
      # Which port do pods selected by this service expose?
      targetPort: 8080
  type: ClusterIP
