apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      # Which port on the node is the service available through?
      nodePort: 30080 #optional, if skipped random port will allocate(default: 30000-32767)
      # Inside the cluster, what port does the service expose?
      port: 80
      # Which port do pods selected by this service expose?
      targetPort: 80
    - name: https
      protocol: TCP
      # Which port on the node is the service available through?
      nodePort: 30443 #optional, if skipped random port will allocate(default: 30000-32767)
      # Inside the cluster, what port does the service expose?
      port: 443
      # Which port do pods selected by this service expose?
      targetPort: 443
  type: NodePort
