{{- if .Values.ingress.tls }}
---
  {{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
data:
  tls.crt: {{ .secret.crt }}
  tls.key: {{ .secret.key }}
type: kubernetes.io/tls
  {{- end }}
{{- end }}

