apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: frontend
        version: 1.0.0
    spec:
      containers:
        - name: frontend
          image: bijoydocker/kubernetes-beginner-frontend:latest
          ports:
            - containerPort: 3000
          env:
              # Use secret in real usage
            - name: WRITER_HOST
              value: "54.89.138.65"
            - name: WRITER_PORT
              value: "31150"
            - name: READER_HOST
              value: "54.89.138.65"
            - name: READERT_PORT
              value: "30661"
      nodeSelector:
        node-type: app