apiVersion: v1   ## equicalent to kubectl expose deployment/my-nginx
kind: Service
metadata:
  name: db
spec:
  # clusterIP: None
  selector:
    app: db
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: db
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: db
        version: 1.0.0
    spec:
      containers:
        - name: db
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
              # Use secret in real usage
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          volumeMounts:
          - name: db-data
            mountPath: /data/db
      volumes:
        - name: db-data
          emptyDir: {}
      nodeSelector:
        node-type: storage
---
apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  # clusterIP: None
  selector:
    app: amqp
  ports:
    - name: api
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: amqp
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: amqp
        version: 1.0.0
    spec:
      containers:
        - name: amqp
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
              # Use secret in real usage
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
          volumeMounts:
          - name: queue-data
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: queue-data
          emptyDir: {}
      nodeSelector:
        node-type: storage