apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: db
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: db
        version: 1.0.0
    spec:
      containers:
        - name: db
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
              # Use secret in real usage
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          volumeMounts:
          - name: db-data
            mountPath: /data/db
      volumes:
        - name: db-data
          emptyDir: {}
      nodeSelector:
        node-type: storage

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: queue-deployment
spec:
  selector:
    matchLabels:
      app: amqp
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      # namespace: dev
      labels:
        app: amqp
        version: 1.0.0
    spec:
      containers:
        - name: amqp
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
              # Use secret in real usage
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
          volumeMounts:
          - name: queue-data
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: queue-data
          emptyDir: {}
      nodeSelector:
        node-type: storage