apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http